### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'reset'

### ISSUE THREAD

**Issue by harritaylor** [williamFalcon/pytorch-lightning#196]
I was just trying to train on ubuntu (over ssh) and got this error:
```
Traceback (most recent call last):
  File "vggish_trainer.py", line 88, in <module>
    main(hyperparams)
  File "vggish_trainer.py", line 58, in main
    trainer.fit(model)
  File "/home/hlt/.conda/lib/python3.7/site-packages/pytorch_lightning/models/trainer.py", line 554, in fit
    self.__single_gpu_train(model)
  File "/home/hlt/.conda/lib/python3.7/site-packages/pytorch_lightning/models/trainer.py", line 602, in __single_gpu_train
    self.__run_pretrain_routine(model)
  File "/home/hlt/.conda/lib/python3.7/site-packages/pytorch_lightning/models/trainer.py", line 795, in __run_pretrain_routine
    self.__train()
  File "/home/hlt/.conda/lib/python3.7/site-packages/pytorch_lightning/models/trainer.py", line 811, in __train
    self.progress_bar.reset(self.total_batches)
AttributeError: 'tqdm' object has no attribute 'reset'
```

The code worked fine on CPU on MacOS, any ideas about what might be going wrong here?

**Comment by harritaylor** [comment]
Issue disappeared when upgraded to `tqdm==4.35.0`
