### ISSUE TITLE
Cannot load saved model.

### ISSUE THREAD

**Issue by lkhphuc** [williamFalcon/pytorch-lightning#26]
I cannot load model back after saved, using `load_from_metrics`:
```
Traceback (most recent call last):
  File "eval-metric.py", line 60, in <module>
    main(hyperparams)
  File "eval-metric.py", line 32, in main
    on_gpu=False, map_location=None)
  File "/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/root_module/root_module.py", line 112, in load_from_metrics
    model = cls(hparams)
  File "/home/jupyter/kaggle-CellSignal/arcface_module.py", line 74, in __init__
    super().__init__(hparams)
  File "/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/root_module/root_module.py", line 12, in __init__
    super(LightningModule, self).__init__(*args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```
Really don't know what went wrong.

**Comment by williamFalcon** [comment]
can you put the code for your model here? and also the loading portion

**Comment by williamFalcon** [comment]
make sure you’re also running the latest version. 

hparams for instance no longer needs to be added to rhe superclass init. 

look at the example on the core readme

**Comment by williamFalcon** [comment]
[This test](https://github.com/williamFalcon/pytorch-lightning/blob/master/tests/test_models.py#L224) specifically tests to make sure models can be saved and loaded.

My hunch is that hparams in your model is causing an issue (doesn't conform with what's expected).

**Comment by lkhphuc** [comment]
Thank, I will take a look. Does the fact that my model was saved on previous version and I'm trying to load it on this version, break the compatability?

**Comment by lkhphuc** [comment]
Ok I updated my model template according to the latest version. Turned out there are some breaking changes in the init and dataloader too.
It's OK now. Thank for your help.

**Comment by calclavia** [comment]
I got stuck on this issue as well and I'm getting a similar error when trying to `load_from_metrics`:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/bernard/asr/test.py", line 12, in <module>
    tags_csv=tags_csv
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/root_module/root_module.py", line 154, in load_from_metrics
    model = cls(hparams)
  File "/workspace/bernard/asr/system.py", line 14, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/root_module/root_module.py", line 14, in __init__
    super(LightningModule, self).__init__(*args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```
