### ISSUE TITLE
AttributeError: 'TTNamespace' object has no attribute 'drop_prob'

### ISSUE THREAD

**Issue by dguera** [williamFalcon/pytorch-lightning#30]
Got the following error while running the [Demo](https://github.com/williamFalcon/pytorch-lightning#demo) examples:

`python single_gpu_node_template.py --gpus "0,1,2,3"`

> Traceback (most recent call last):
  File "single_gpu_node_template.py", line 112, in <module>
    main(hyperparams)
  File "single_gpu_node_template.py", line 33, in main
    model = LightningTemplateModel(hparams)
  File "/home/dgueraco/projects/pytorch-lightning/pytorch_lightning/examples/new_project_templates/lightning_module_template.py", line 37, in __init__
    self.__build_model()
  File "/home/dgueraco/projects/pytorch-lightning/pytorch_lightning/examples/new_project_templates/lightning_module_template.py", line 49, in __build_model
    self.c_d1_drop = nn.Dropout(self.hparams.drop_prob)
AttributeError: 'TTNamespace' object has no attribute 'drop_prob'

**Comment by williamFalcon** [comment]
thanks for pointing out. Just pushed a fix. Try again
