### ISSUE TITLE
ModuleNotFoundError: No module named 'demo'

### ISSUE THREAD

**Issue by forhonourlx** [williamFalcon/pytorch-lightning#4]
simon:~/Desktop/pytorch-lightning/demo$ python fully_featured_trainer.py
Traceback (most recent call last):
  File "fully_featured_trainer.py", line 20, in <module>
    from demo.example_model import ExampleModel
ModuleNotFoundError: No module named 'demo'

**Comment by williamFalcon** [comment]
fixed! try again

**Comment by forhonourlx** [comment]
Hi William,
@williamFalcon 

simon@simon:~/Desktop/pytorch-lightning/demo$ python fully_featured_trainer.py
RUNNING MULTI GPU. GPU ids: ['0']
loading model...
running on gpu...
model built
gpu available: True, used: False
[Errno 13] Permission denied: '/Users'
Caught exception in worker thread [Errno 13] Permission denied: '/Users'
...
in example_model.py:
parser.add_argument('--data_root', default='/Users/williamfalcon/Developer/personal/research_lib/research_proj/datasets/mnist', type=str)
in model_template.py:
parser.add_argument('--data_root', default='/Users/williamfalcon/Developer/personal/research_lib/research_proj/datasets/mnist', type=str)
in embeddings.py:
    emb = PretrainedEmbedding(
        embedding_path='/Users/waf/Developer/NGV/research-fermat/fermat/.vector_cache/glove.840B.300d.txt',
        embedding_dim=300,
        task_vocab={'hello': 1, 'world': 2}
    )

**Comment by williamFalcon** [comment]
wait... fixing again

**Comment by forhonourlx** [comment]
Hi William,
@williamFalcon 
After change the path,
One more when cuda training...

simon@simon-X299:~/Desktop/pytorch-lightning/demo$ python fully_featured_trainer.py
RUNNING MULTI GPU. GPU ids: ['0']
loading model...
running on gpu...
model built
gpu available: True, used: False
        Name         Type  Params
0       c_d1       Linear  392500
1    c_d1_bn  BatchNorm1d    1000
2  c_d1_drop      Dropout       0
3       c_d2       Linear    5010
validating...
Caught exception in worker thread expected type torch.FloatTensor but got torch.cuda.FloatTensor
Traceback (most recent call last):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/test_tube/argparse_hopt.py", line 29, in optimize_parallel_gpu_private
    results = train_function(trial_params)
  File "fully_featured_trainer.py", line 36, in main_local
    main(hparams, None, None)
  File "fully_featured_trainer.py", line 105, in main
    trainer.fit(model)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py", line 223, in fit
    _ = self.validate(model, self.val_dataloader, max_batches=self.nb_sanity_val_steps)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/pytorch_lightning/models/trainer.py", line 154, in validate
    for i, data_batch in enumerate(dataloader):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 95, in __getitem__
    img = self.transform(img)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor
