### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by forhonourlx** [williamFalcon/pytorch-lightning#5]
simon:~/Desktop/pytorch-lightning/demo$ python fully_featured_trainer.py
Traceback (most recent call last):
  File "fully_featured_trainer.py", line 162, in <module>
    parent_parser = get_default_parser(strategy='random_search', root_dir=root_dir)
  File "fully_featured_trainer.py", line 111, in get_default_parser
    add_default_args(parser, root_dir, possible_model_names, SEED)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/pytorch_lightning/utils/arg_parse.py", line 37, in add_default_args
    parser.add_argument('--model_name', default='', help=','.join(possible_model_names))
TypeError: can only join an iterable

**Comment by williamFalcon** [comment]
fixed. try again!
